name:    pluto
version: "0.0.0"

dependencies:

- base >= 4.7 && < 5
- yesod
- yesod-core
- yesod-auth
- yesod-auth-oauth2
- yesod-static
- yesod-form
- yesod-eventsource
- classy-prelude
- classy-prelude-conduit
- classy-prelude-yesod
- bytestring
- text
- persistent
- persistent-postgresql
- persistent-template
- template-haskell
- shakespeare
- hjsmin
- monad-control
- wai-extra
- yaml
- http-client-tls
- http-conduit
- directory
- warp
- data-default
- aeson
- conduit
- monad-logger
- fast-logger
- wai-logger
- file-embed
- safe
- unordered-containers
- containers
- vector
- time
- case-insensitive
- wai
- foreign-store

# The library contains all of our application code. The executable
# defined below is just a thin wrapper.
library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -fwarn-tabs
  - -O2

# Runnable executable for our application
executables:
  pluto:
    main: main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pluto

# Test suite
tests:
  pluto-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: -Wall
    dependencies:
    - pluto
    - hspec >=2.0.0
    - yesod-test
