name:    cataract
version: "0.0.0"

dependencies:
- aeson
- base >= 4.7 && < 5
- binary
- blaze-markup
- bytestring
- case-insensitive
- classy-prelude
- classy-prelude-conduit
- classy-prelude-yesod
- conduit
- conduit-extra
- containers
- cryptonite
- data-default
- directory
- esqueleto
- fast-logger
- file-embed
- foreign-store
- hedgehog
- hjsmin
- hspec
- hspec-hedgehog
- http-client-tls
- http-conduit
- lens
- memory
- monad-control
- monad-logger
- mtl
- persistent
- persistent-postgresql
- persistent-template
- safe
- shakespeare
- template-haskell
- text
- text-conversions
- time
- unordered-containers
- uuid
- vector
- wai
- wai-cors
- wai-extra
- wai-logger
- warp
- wreq
- yaml
- yesod
- yesod-auth
- yesod-auth-oauth2
- yesod-core
- yesod-eventsource
- yesod-form
- yesod-static

default-extensions:
- DeriveGeneric
- ImportQualifiedPost
- LambdaCase
- NoImplicitPrelude
- OverloadedStrings
- RecordWildCards
- TypeApplications

# The library contains all of our application code. The executable
# defined below is just a thin wrapper.
library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -fwarn-tabs
  - -O2

# Runnable executable for our application
executables:
  cataract:
    main: main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cataract

# Test suite
tests:
  cataract-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: -Wall
    dependencies:
    - cataract
    - hspec >=2.0.0
    - yesod-test
